// This file is auto-generated by TanStack Router
// Do not edit manually

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as EventsIdRoute } from './routes/events/$id'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/events/$id': {
      preLoaderRoute: typeof EventsIdRoute
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  EventsIdRoute,
])
